<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <div class="row">
            <div class="col-md">
                <form class="form-group" method="post" action="/registrar">
                    <h2 class="text-dark" style="text-align:center">Cadastro de usuários</h2>
                    <hr />
                    <input name="nome" type="text" placeholder="Nome" class="form-control" value="<?= $this->view->usuario['nome']?>" required /> <br />
                    <input name="login" type="text" placeholder="Login" class="form-control" value="<?= $this->view->usuario['login']?>" required /> <br />
                    <input name="senha" type="password" placeholder="Senha" class="form-control" value="<?= $this->view->usuario['senha']?>" required /> <br />
                    <select name="tipo_usuario" class="custom-select custom-select-md mb-3">
                        <option value="3">Cliente</option>
                        <option value="2">Visualizador</option>
                        <option value="1">Administrador</option>
                    </select>
                    <button type="submit" class="btn btn-outline-success">Salvar</button>
                    <a class="btn btn-outline-warning" href="/cadastrar">Limpar campos</a>
                    <a class="btn btn-outline-danger" href="/usuario">Voltar</a>

                    <div class="row">
                        <?php if ($this->view->erroCadastro) { ?>
                            <small class="form-text text-danger"> *Erro ao tentar realizar o cadastro, usuário já cadastrado.* </small>
                        <?php } ?>
                    </div>

                </form>
            </div>
        </div>
    </div>

</div>