<script language="javascript" src="/js/carregaimg.js"></script>

<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <div class="row">
            <div class="col-md">
                <form class="form-group" method="post" action="/registrarprod">
                    <h2 class="text-dark" style="text-align:center">Cadastro de Produtos</h2>
                    <hr />
                    <input name="nome" type="text" placeholder="Nome" class="form-control" required /> <br />
                    <textarea name="descricao" type="text" placeholder="Descrição" class="form-control" required></textarea> <br />
                    
                    <div class="text-center" id="renderiza_imagem">
                        <!-- Exibe a imagem aqui -->
                    </div>

                    <label>Selecione a imagem</label>
                    <select name="imagem" class="custom-select custom-select-md mb-3" onchange="loadImagem(this.value)">
                        <?php foreach ($this->view->imagem as $indice => $imagem) { ?>
                            <option value="/img/produto/<?=$imagem['nome']?>"><?= $imagem['nome'] ?></option>
                        <?php } ?>
                    </select>

                    <!-- tipo do produto -->
                    <label>Selecione o tipo do produto</label>
                    <select name="tipo" class="custom-select custom-select-md mb-3" required>
                        <option value="hamburguer">Hamburguer</option>
                        <option value="batata">Batata</option>
                        <option value="bebida">Bebida</option>
                        <option valure="combo">Combo</option>
                    </select>
                    <!-- fim tipo -->
                    <input name="preco" step="0.01" type="number" placeholder="Preço" class="form-control" value="<?= $this->view->produto['preco'] ?>" required /> <br />
                    <label>Promoção:</label>
                    <select name="promocao" class="custom-select custom-select-md mb-3">
                        <option value="0">Não</option>
                        <option value="1">Sim</option>
                    </select>

                    <button type="submit" class="btn btn-outline-success">Salvar</button>
                    <button type="reset" class="btn btn-outline-warning">Limpar campos</button>
                    <a class="btn btn-outline-danger" href="/produto">Voltar</a>

                    <div class="row">
                        <?php if ($this->view->erroCadastro) { ?>
                            <small class="form-text text-danger"> *Erro ao tentar realizar o cadastro, produto com nome já cadastrado.* </small>
                        <?php } ?>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>