<link rel="stylesheet" href="/css/home.css">

<div class="container">
    <div class="row justify-content-center">
        <div class="jumbotron">
            <h1 class="display-4 text-success">Seu pedido foi processado! </h1>
            <p class="lead">Já está em andamento, aguarde a entrega do pedido.</p>
            <hr class="my-4">
            <a class="btn btn-primary btn-lg" href="/produto" role="button">Realizar novo pedido</a>
        </div>
    </div>
</div>