<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>SIGR - Sistema gerencial para restaurante</title>

		<link rel="stylesheet" href="/css/bootstrap.min.css">

		<script src="/js/jquery-3.3.1.slim.min.js"></script>
		
		<script src="/js/popper.min.js"></script>
		
		<script src="/js/bootstrap.min.js"></script>

		<!--
			Incorporar CSS	
		<link rel="stylesheet" href="/css/style.css" /> 
		-->
		
		<link href="/css/signin.css" rel="stylesheet">
		<link href="/css/sticky-footer-navbar.css" rel="stylesheet">
	</head>

	<body>
		<?= $this->content() ?>
	</body>

</html>